### ISSUE TITLE
'cookies' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by i-Senku** [sbertix/Swiftagram#101]
i get this error in latest version.
`'cookies' is inaccessible due to 'internal' protection level`

**Comment by i-Senku** [comment]
and follow or unfollow functions doesnt exit your FriendShip class `Endpoint.Friendship.follow(userPK)` .

**Comment by sbertix** [comment]
Are you importing `SwiftagramCrypto`? 
Following and unfollowing requires importing that library too, not only `Swiftagram`.

**Comment by sbertix** [comment]
> i get this error in latest version.
> 
> `'cookies' is inaccessible due to 'internal' protection level`

Does this happen in your code or is it returned somewhere from within `Swiftagram`? 
If the issue is in your code then it's by design: I'm limiting access to cookies in a way to limit abuses. If it's in `Swiftagram` would you let me know where it fires so I can fix it?

**Comment by i-Senku** [comment]
> > i get this error in latest version.
> > `'cookies' is inaccessible due to 'internal' protection level`
> 
> Does this happen in your code or is it returned somewhere from within `Swiftagram`?
> If the issue is in your code then it's by design: I'm limiting access to cookies in a way to limit abuses. If it's in `Swiftagram` would you let me know where it fires so I can fix it?

```

        secretData.cookies.forEach { (cookie) in
            if cookie.name == "csrftoken" {
                token = cookie.value
            }
            cookieValue.append(cookie.name+"="+cookie.value+";")
        }
```

i was using this code to follow and unfollow.But now i dont need because follow and unfollow are working when i import SwiftagramCrypto . Thanks for everything 👍
