### ISSUE TITLE
Login agent

### ISSUE THREAD

**Issue by MariaJsn** [sbertix/Swiftagram#102]
Hey Sbertix,

Is there any way to change login device? I want to use apple device instead of android.
When I login to instagram with Swiftagram, it says you logged with Samsung SM-G981B · Chrome Mobile.

Thanks,
Maria

**Comment by sbertix** [comment]
Hey @MariaJsn.
Sure,  just do this:

```swift
Client.default = .current ?? .iPhone11ProMax
```

Or pass a new `Client` when authenticating with `WebViewAuthenticator` or `BasicAuthenticator`.

```swift
BasicAuthenticator(client: .current ?? .iPhone11ProMax)
   […]
```

Please keep in mind `Client`s are linked to authentication `Secret`s: you will need to log in again in order to change the device you are using 😊
