### ISSUE TITLE
Friendship is nil when I get user summary

### ISSUE THREAD

**Issue by lijing8989** [sbertix/Swiftagram#104]
I was going to get "friendship" by following api call.

>             Endpoint.User.summary(for: identifier)
>                 .unlocking(with: secret)
>                 .task { (result) in
>                     switch result {
>                     case .success(let user):
>                         let friendship = userUnit.user?.friendship
>                     case .failure(let error):
>                         comp(.failure(error))
>                     }
>                 }
>                 .resume()

But "friendship" is nil.
I am following him, and he is also following me, so friendship should be exist.
Here, secret is my account's one.
And I can get all other info except "friendship".

**Comment by lijing8989** [comment]
And I get friendship as nil when I get followers and followings.

**Comment by sbertix** [comment]
Hey @lijing8989, this appears to be a change in **Instagram** behavior, unrelated to **Swiftagram**. 
Friendship status is no longer returned when asking for a user's summary, meaning you will need to interrogate `Endpoint.Friendship.summary(for:)` specifically.

**Comment by lijing8989** [comment]
@sbertix 
Thanks for your response.
> Endpoint.Friendship.following
> Endpoint.Friendship.followed
Don't these apis also return "friendsship"?

**Comment by serhiy1017** [comment]
I meet the above same issue.
So is the attribute "friendship" nil always for all cases?
If yes, then you should remove the "friendship" in your framework.

**Comment by sbertix** [comment]
The `friendship` property used to be populated when calling `Endpoint.User.summar(for:)` and only that. 
It was never populated for `Endpoint.Friendship.following(_:)` or `Endpoint.Friendship.followed(by:)`. As Instagram removed it from the response, I'm gonna remove it from the model too.
