### ISSUE TITLE
Can't get saved Secret in Widget Extension

### ISSUE THREAD

**Issue by serhiy1017** [sbertix/Swiftagram#105]
@sbertix
There is a Widget Extension in my app.
I can get saved secret in main app, but in the extension.
I am using following code.
`KeychainStorage<Secret>().all()`
Could you support this issue?

**Comment by sbertix** [comment]
Hey @serhiy1017. 
This is not a bug. As a widget is for all intents and purposes a separate app, you need to store your `Secret` in a `KeychainStorage` with a shared access group. 
Consider reading [this](https://developer.apple.com/documentation/security/keychain_services/keychain_items/sharing_access_to_keychain_items_among_a_collection_of_apps).
