### ISSUE TITLE
Endpoint for follower/following search

### ISSUE THREAD

**Issue by senolatac** [sbertix/Swiftagram#111]
In swiftagram, you have endpoint to fetch user follower/following list page by page. But I wonder how can I search follower/following users? Is there an endpoint for it?

For Example:

v1/user/friendship/follower?q=abc
Show only my followers, username/name includes "abc"

**Comment by sbertix** [comment]
Hey @senolatac,

No, there isn't a method querying followers/following by name/username, right now. 

It's mostly cause I forgot to add it back 😅

If it's still working like it should I'll push an update within a couple hours.
