### ISSUE TITLE
How to delete Android agent name ? :(

### ISSUE THREAD

**Issue by aslios** [sbertix/Swiftagram#113]
Hi Sbertix,
I want to change login device name? I want use iphone or other apple device name instead of android and when i login via SwiftGram instagram send to me mail as "some android device (samsung xxxx ) login etc. ..."
i dont want see android device name.can i write "iphone" + "device name" ? (like "aslios iphone" )
Thank you so much

**Comment by sbertix** [comment]
Hey @aslios,

There are many issues closed already regarding this feature. 
All you need to do is set the following line on app launch.

```swift
Client.default = .current ?? .iPhone11Max
```

This will try and detect the user's iPhone. But if it's not an iPhone, it's gonna use the iPhone 11 Max as reference.
