### ISSUE TITLE
Trying to run the code on watchOS is not working

### ISSUE THREAD

**Issue by ramz30011** [sbertix/Swiftagram#115]
Trying to build for watchOS but getting errors as per the attached image :
![Screen Shot 2020-12-18 at 3 04 17 AM](https://user-images.githubusercontent.com/62383141/102561651-e2166280-40dd-11eb-8596-7d487f3c2736.png)

**Comment by sbertix** [comment]
Hey @ramz30011, thank you for pointing this out. 
I'll push a new version fixing this issue within a couple hours 💪
