### ISSUE TITLE
Endpoint Media Posts Upload is not working

### ISSUE THREAD

**Issue by khaliddd** [sbertix/Swiftagram#120]
Hi, 

Endpoint to upload image to instagram is not working. 
I get success but media is `nil` and can't see any post on instagram. 

My code is : 

```swift
Endpoint.Media.Posts.upload(image: image, captioned: "test")
            .unlocking(with: secret)
            .task { (response) in
                if case .success(let unit) = response {
                    // unit.media is nil
                }
                else if case .failure(let error) = response {
                    print(error.localizedDescription)
                }
            }.resume()
```

**Comment by sbertix** [comment]
Hey @khaliddd, 
I'm unable to test it right now, I hope I can get to it later today. 
Would you be able to confirm whether it works properly WITHOUT adding a caption to the photo? Cause we had similar issues in the past and it might be related to that.

**Comment by khaliddd** [comment]
@sbertix its not working even WITHOUT caption.

**Comment by sbertix** [comment]
Hahaha "great". I hope to get to test it soon.
