### ISSUE TITLE
Crash in Media.location.coordinates

### ISSUE THREAD

**Issue by khaliddd** [sbertix/Swiftagram#124]
Hi, 

In some unknown cases app crashes when I access coordinates of a post (media.location.coordinates). 

Error description : Swift runtime failure: Unexpectedly found nil while implicitly unwrapping an Optional value 

location is optional value, but you force unwrap coordinate value. 

(definitely I access coordinate value only if location is not nil)

**Comment by sbertix** [comment]
Hey @khaliddd,

thank you for pointing this out 💪 
For some reason I assumed they would always be populated, but they're not. 
I'm pushing a new version rn.

**Comment by khaliddd** [comment]
Thank you for the quick response.
