### ISSUE TITLE
Pagination in Endpoint.Media.timeline(startingAt:) ignoring start

### ISSUE THREAD

**Issue by dramikei** [sbertix/Swiftagram#126]
- [x] I've searched past issues and I couldn't find reference to this. 

**Swiftagram version**
`4.2.5`

**Describe the bug**
When calling `Endpoint.Media.Posts.timeline(startingAt: )` with correct maxId and secret, the resulting wrapper is the same when called using `Endpoint.Media.Posts.timeline()`. Making pagination unusable.

**To reproduce**
1) Call Endpoint.Media.Posts.timeline().unlocking(with: secret)...
2) extract next_max_id
3) Call Endpoint.Media.Posts.timeline(startingAt: next_max_id)

**Expected behavior**
Request should return next page data.

**Additional context**
Upon checking Swiftagram [source code](https://github.com/sbertix/Swiftagram/blob/08eeab087ef8e87f49e352025b3e45fda4b9ec60/Sources/Swiftagram/Endpoints/EndpointMedia.swift#L182) I found out that "startingAt page" parameter was not being used anywhere in the code. 

**Device and system**
macOS 11.0.1, Watch Simulator.

**Comment by sbertix** [comment]
Hey @dramikei,
sorry I completely forgot about this. 

> Upon checking Swiftagram source code I found out that "startingAt page" parameter was not being used anywhere in the code.

If that's the case it's gonna be an easy fix. I'm gonna work on this immediately 💪

**Comment by sbertix** [comment]
So I'm releasing `4.2.8` with a fix. 

Please keep in mind, however, as I mentioned before, storing the `nextMaxId` and then using it to call the endpoint again is not the suggested implementation. Either way, it's not a "bad way", it's just less efficient, so feel free. Just a suggestion 💪
