### ISSUE TITLE
adding send Direct message

### ISSUE THREAD

**Issue by ramimoghrabi** [sbertix/Swiftagram#133]
is it possible to add send Direct message from this library ?

**Comment by sbertix** [comment]
Hey @ramimoghrabi, 

For request and enhancements you should use [**Discussions**](https://github.com/sbertix/Swiftagram/discussions) not **Issues**, as this is not an error/bug, and it will be archived after this response. 

The feature has already been requested and **it will not be supported**. You can find more [here](https://github.com/sbertix/Swiftagram/discussions/122).

**Comment by sbertix** [comment]
Hey @ramimoghrabi, 

I've decided to ease the self-imposed restrictions I had put on sending dms. 
As of `5.0.0` anyone will be able to send text only messages to **already existing** conversations. 
I feel like this is a good enough compromise between providing the most complete API wrapper, and caution about possible misuses. 

I'm writing this here just for reference.
