### ISSUE TITLE
Followers/Following User Name

### ISSUE THREAD

**Issue by MariaJsn** [sbertix/Swiftagram#148]
Hi @sbertix :)

In api followings and followers endpoints returns nil for user name.
Can you check it please?

Thanks,
Maria

**Comment by sbertix** [comment]
Hey @MariaJsn, 

Are you sure? 🤔 
I haven't been able to replicate this using `Endpoint.Friendship.following(_:)` and `Endpoint.Friendship.followed(by:)`… 
The `username` property is still there in the response and it's correctly captured by the `Wrapper` and, therefore, `User`. 

Do you have more info on what's going wrong on your side? 😊

**Comment by MariaJsn** [comment]
I got the point so sorry it is my mistake
