### ISSUE TITLE
Login with facebook not working

### ISSUE THREAD

**Issue by khaliddd** [sbertix/Swiftagram#157]
Hi, 

Continue with facebook login is not working, on web view it open the instagram feeds page, but WebViewAuthenticator gives an error : 

The operation couldn’t be completed. (Swiftagram.WebViewAuthenticatorError error 0.)

Swiftagram version : 4.2.7

**Comment by sbertix** [comment]
Hey @khaliddd, 

🤔 
Mmh… I've never actually thought about the "Continue with Facebook" option and I don't really have a way to test it, either, unfortunately. I just assumed they would use the same cookies. 
Do you have a way to test it yourself so we can figure it out "live" on a Zoom call or something?

**Comment by khaliddd** [comment]
Hi @sbertix , 
sorry for getting back late : 

When we login via facebook we get the following cookies: 

```
[<NSHTTPCookie
	version:1
	name:ds_user_id
	value:46465954500
	expiresDate:'2021-06-23 09:15:17 +0000'
	created:'2021-03-25 09:15:17 +0000'
	sessionOnly:FALSE
	domain:.instagram.com
	partition:none
	sameSite:none
	path:/
	isSecure:TRUE
 path:"/" isSecure:TRUE>, <NSHTTPCookie
	version:1
	name:sessionid
	value:46465954500%3AFBkFJZgd6dpyvO%3A14
	expiresDate:'2022-03-25 09:14:42 +0000'
	created:'2021-03-25 09:14:42 +0000'
	sessionOnly:FALSE
	domain:.instagram.com
	partition:none
	sameSite:none
	path:/
	isSecure:TRUE
	isHTTPOnly: YES
 path:"/" isSecure:TRUE isHTTPOnly: YES>]
```
 
 
 There is no cookie for "csrftoken" 
 
 and you validate cookies like this: 
 
 `var containsAuthenticationCookies: Bool {
        Set(map(\.name)).intersection(["ds_user_id", "sessionid", "csrftoken"]).count == 3
    }`

is there any quick fix for it ?

Thanks in advance

**Comment by sbertix** [comment]
I've deleted the comment just in case the cookies could be actually used to login @khaliddd. 

I'm not really sure how it would work with all endpoints requiring the CSRF token... 🤔 

I'll try to find a way to test it in the next few days. 
Possibly for `5.0.0`.

**Comment by khaliddd** [comment]
okay thank you.

**Comment by khaliddd** [comment]
Hi @sbertix , 

for some strange reasons it works when I debug it with break points , I guess it works if there is some delay , 

if I remove breakpoints it does not work. 

do you have any idea what could be the issue ?

**Comment by sbertix** [comment]
I'm assuming cookies are validated by **Swiftagram** before they're actually set. 
I know it was an issue in the past, in the implementation I had written for **SwiftyInsta**, but I never saw it happen in `WebViewAuthenticator`. I'm definitely gonna fix this though.

**Comment by sbertix** [comment]
Hey @khaliddd, 

I've changed the authentication flow in `5.0.0`: it's still based on the old behavior (i.e. the actual steps are the same but I improved on the code), but unfortunately I can't test it to see whether it's enough or not to have it work with Facebook. 
Do you mind cloning the `development` branch and testing the authentication in the _Followers_ example and give me some feedback? Thanks.

**Comment by khaliddd** [comment]
Hi @sbertix, 

Sorry, I was bit busy.
I'll test it today or tomorrow and will update you.

**Comment by khaliddd** [comment]
@sbertix I am getting an error in development branch, can you please help me to fix it. 

![Screen Shot 2021-04-14 at 3 07 00 PM](https://user-images.githubusercontent.com/2604040/114693924-7ebadb00-9d33-11eb-8860-15d459e65939.png)

**Comment by sbertix** [comment]
> @sbertix I am getting an error in development branch, can you please help me to fix it.
> 
> ![Screen Shot 2021-04-14 at 3 07 00 PM](https://user-images.githubusercontent.com/2604040/114693924-7ebadb00-9d33-11eb-8860-15d459e65939.png)

I'm assuming you have a dependency to the older **ComposableRequest** in your code when adding the new one. 
There's no point in adding it to your actual project right now though, as it's not ready yet. 
I was just wondering if you could clone **Swiftagram** and test login in the _Followers_ example (so I also know how the actual authentication is implemented in the client).

**Comment by khaliddd** [comment]
@sbertix : 
its working

**Comment by sbertix** [comment]
Great @khaliddd 💪 
I'm gonna close the issue once `5.0.0` is out then. 
Thanks man
