### ISSUE TITLE
Missing Followers 

### ISSUE THREAD

**Issue by MariaJsn** [sbertix/Swiftagram#161]
Hi Sbertix :)

There is a problem when getting followers list.

I have two instagram account 
First one of them has 190 followers and 17 following -> I can get the following and follower list correctly.
Second account I have 214 followers and 301 following -> I can get the followings correctly but in followers I can get 194 instead of 214.

Really I could not understand why it is not working for some accounts. (Tried with my friends account too and some of them working and others not). 

This is my code:

var followerIs = [String]()
Endpoint.Friendship.following(secret.identifier)
            .unlocking(with: secret)
            .task(maxLength: .max,
                  onComplete: { _ in
                    
                    print(followers.count) -> Returns 194 instead of 214
                    
                  },
                  onChange: { [weak self] in
                    
                    let data = try? $0.get()
                   
                    data?.users?.forEach({user in
                        
                       followerIsappend(user.identifier)

                    })
            })
            .resume()

**Comment by sbertix** [comment]
Hey @MariaJsn,

Followers and following count are not updated immediately as people deactivate their account, or delete it, etc. 

This is not a bug: you're simply fetching only actual followers/following, minus the ones who might have blocked you (which is for sure a minor factor but that's another reason why counters are overestimated). 

If you go to the app and count followers/following manually, you'll see that despite saying 214 you will only find 194. 

Again, not a bug.

**Comment by MariaJsn** [comment]
But When I login my account and request for my friends followers/followings list, it returns correct values. And also some of the accounts there is a diff more than 50 user

**Comment by sbertix** [comment]
> But When I login my account and request for my friends followers/followings list, it returns correct values. And also some of the accounts there is a diff more than 50 user

When checking the same profile? 
Let's say you're checking Instagram followers, you get 50 more followers when using another account? 
Assuming all 50 accounts haven't blocked you, which wouldn't make sense, the reason for this might be rate limiting. Followers and following endpoints are heavily restricted by Instagram and you're probably making too many requests. 
This is not something I can control, nor a bug in **Swiftagram**, it's just **Instagram** making sure people don't misuse their systems.

Again though, do not expect counters and the actual amount followers/following to **ever** be the same, cause they're not.
