### ISSUE TITLE
Swift compile error with watchOS app extension in 5.0.0 beta

### ISSUE THREAD

**Issue by Bubba8291** [sbertix/Swiftagram#166]
- [x] I've searched past issues and I couldn't find reference to this. 

**Swiftagram version**
development branch

**Describe the bug**
A bunch of errors show up including `Cannot find 'CGSize' in scope` when building for watchOS

**To reproduce**
1. Create a iOS Xcode project with a watchOS app extension
2. Add Swiftagram with SPM on the development branch
3. Import Swiftagram and SwiftagramCrypto into the watchOS app extension code
4. Run the project and the build fails

**Expected behavior**
Run without any errors

**Additional context**
Screenshot provided
Error doesn't happen in the stable release

**Device and system**
macOS 11.2.3, Xcode 12.4

<img width="262" alt="Screen Shot 2021-04-14 at 5 42 44 PM" src="https://user-images.githubusercontent.com/37317442/114798281-de23e580-9d49-11eb-92c4-3d97f3e22874.png">

**Comment by sbertix** [comment]
Hey @Bubba8291,

Please keep in mind issues regarding beta versions in the `development` branch will not be (officially) considered. 

However, I can't tell you this looks like an `import` oversight on my side and I'm definitely gonna fix it by the end of the day 😊

Thank you for pointing this out 💪

**Comment by sbertix** [comment]
Hey @Bubba8291, 

This should have been fixed with the last commit to the `development` branch 💪
