### ISSUE TITLE
Unsupported browser disclaimer while logging in with Facebook

### ISSUE THREAD

**Issue by biox86** [sbertix/Swiftagram#180]
Swiftagram version
4.2.10

When the Client.default is set to .iPhone11ProMax, if you try to log with Facebook you can see a big disclaimer at the top of the webview saying "unsupported browser".
The login works correctly anyway, but it feels like there's something wrong seeing that huge banner at the top of the view. 

1. Set the Client.default to . iPhone11ProMax
2. Login with a webview
3. Tap on "Continue with Facebook"
4. See the disclaimer

Device and system
macOS 10.15.7, iPhone Simulator 14.4, iPhone Device 14.4.2

**Comment by sbertix** [comment]
Hey @biox86, 

Thank you for pointing it out. 
I'm gonna see that this is fixed in time for `5.0.0`, which I'm hopefully releasing by the end of this week. Fingers crossed.

**Comment by biox86** [comment]
Great news, thanks for the super fast response!
