### ISSUE TITLE
Pagination still not working

### ISSUE THREAD

**Issue by sbertix** [sbertix/Swiftagram#188]
Hi @sbertix, 

Pagination is not working in `Endpoint.user(userId).following` 

actually it got worse in the update `5.0.0`, it fetches only one page, 

whereas in previous version it was fetching desired pages but nextId was nil 

can you please check it.

_Originally posted by @khaliddd in https://github.com/sbertix/Swiftagram/discussions/187_

**Comment by sbertix** [comment]
Do you mind sending me a Telegram message with the console output of your request, cause I'm assuming this is related account-specific differences (meaning Instagram might serve different responses according to some user-based parameters) as it all works fine on my end. 

Just add `Logger.default = .init(level: .Response.body)` (or `Logger.default = .init(level: Logger.Level.Response.body)` if you're on older versions of Swift) on launch and [message me the result](https://telegram.me/sbertix), please.

**Comment by khaliddd** [comment]
Hi @sbertix , 

sure no problem , 

can I send you response via email?, as I don't use telegram.

**Comment by sbertix** [comment]
> Hi @sbertix ,
> 
> sure no problem ,
> 
> can I send you response via email?, as I don't use telegram.

Sure 😊 
`stefano@bertagno.com`
