### ISSUE TITLE
Build fails while archiving in `5.0.2`

### ISSUE THREAD

**Issue by khaliddd** [sbertix/Swiftagram#191]
Hi @sbertix, 

I am getting compiler error `No such module 'Combine'` when I try to archive, 

my minimum deployment target is 14, and I am not using swiftUI

![Screen Shot 2021-05-09 at 4 52 49 AM](https://user-images.githubusercontent.com/2604040/117556644-7c267980-b084-11eb-900c-4138ff335229.png)

**Comment by sbertix** [comment]
Hey @khaliddd,

Are you trying to archive an iOS build? 
If your deployment target is less then iOS 13, please follow the `README` instructions on using `5.0.0` on previous platform versions. 

If that's not the case, make sure you're cleaning your project, emptying derived data, removing **Swiftagram** from your dependencies completely, then adding it back.

**Comment by khaliddd** [comment]
yes, for iOS build, 

still not working :(

**Comment by sbertix** [comment]
What version of Xcode are you on?

**Comment by khaliddd** [comment]
Version 12.5 (12E262)

**Comment by sbertix** [comment]
It does not appear to be related with **Swiftagram** per se, still I'm not really sure why **CombineX** would have trouble `import`ing `Combine`… 
I hope I'll get to test it some more either tonight or tomorrow, and if no solution can be found, I'm just gonna drop **CombineX** all together and stick with iOS 13 and above.

**Comment by sbertix** [comment]
Removing **CombineX** did fix the problem and I feel like it's the only way to go… 
I'm not merging yet as it's somehow a "defeat" having to raise deployment version to iOS 13, but find a working version on the `development` branch for now.

**Comment by khaliddd** [comment]
Thanks man
