### ISSUE TITLE
Missing endpoint `reels_media`

### ISSUE THREAD

**Issue by bariscck** [sbertix/Swiftagram#20]
I trying to fetch and display `Stories` with multiple user ids but I could't find `reels_media` endpoint.

This endpoint already exist in [SwiftyInsta](https://github.com/TheM4hd1/SwiftyInsta).
https://github.com/TheM4hd1/SwiftyInsta/blob/e6c43dbbf2b50354842ebfd53ddb71f46aa40313/SwiftyInsta/API/Handlers/StoryHandler.swift#L273

**Comment by sbertix** [comment]
Yep. Definitely planning on adding a wider range of endpoints asap.
I'm working on it in the next few days 💪
