### ISSUE TITLE
`WebViewAuthenticator` not retrieve `Secret`.

### ISSUE THREAD

**Issue by bariscck** [sbertix/Swiftagram#23]
@sbertix thanks for the update `2.0.0`. `WebViewAuthenticator` not retrieve `Secret` in `2.0.0`. `BasicAuthenticator` works fine.

**Comment by sbertix** [comment]
I knew I messed it up somewhere hahaha
I had way too many issues trying to merge this. Apologies, I'll try to fix it by the end of the day.

**Comment by sbertix** [comment]
Do you mind checking if the commit on `development` solves it, please? 😊   
I can't check it myself unfortunately… 
@bariscck

**Comment by bariscck** [comment]
@sbertix sorry for the delayed response, it works fine. Thanks 😊.

**Comment by sbertix** [comment]
Nothing to apologize for 😊
Thanks for pointing out the bug, man 💪
