### ISSUE TITLE
Instagram AJAX Login

### ISSUE THREAD

**Issue by sbertix** [sbertix/Swiftagram#25]
The endpoint used in `BasicAuthenticator` appears to be unreachable, either temporarily or, more likely, due to a change in Instagram authentication process.

As for now, please default to `WebViewAuthenticator` for logging in.

**Comment by MatoMA** [comment]
Hi @sbertix, do you have any plans to support Android API?
Web-Login-Encryption needs AES-GCC (SwCrypt) and Sealed Box (swift-sodium).
Android-Login-Encryption needs RSA and AES-GCC ( all in SwCrypt, one dependence).
Google & Apple want to block cookie usage in browser in the future. I think it is also a good idea to implement Android API as a backup auth method. 

Ref:
https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/
https://github.com/dilame/instagram-private-api/issues/1010

**Comment by sbertix** [comment]
Yep. I had started working on it on the `authentication` branch but I didn't have time to actually finish it.\
And I'm dropping support for Web login entirely.

**Comment by sbertix** [comment]
I'm adding back 2FA support by the end of the day and then I'm pushing the new `BasicAuthenticator` into `SwiftagramCrypto`.\
Just a heads up in case you wanna implement it on **SwiftyInsta** or something @MatoMA 💪

**Comment by sbertix** [comment]
_If you found this useful, please consider starring :star: this repo, or even [sponsoring it](https://paypal.me/sbertix) :dollar:.<br />Even just $1 can help me maintain this._<br />_Thank you for using **Swiftagram**._

**Comment by jerry317** [comment]
@sbertix just donated $50

**Comment by sbertix** [comment]
> @sbertix just donated $50

Really appreciated man. Thank you.
