### ISSUE TITLE
Add response specific types

### ISSUE THREAD

**Issue by sbertix** [sbertix/Swiftagram#26]
As of right now, all endpoints return a generic dynamic `ComposableRequest.Response`.\
Going forward I'm going to implement some `protocol`s for the most common responses.

e.g.
```swift
public protocol User
public extension User where Self: DynamicResponse {
     var username: String? { return self["username"].string() }
}
```

**Comment by Goktug** [comment]
@sbertix  Could you provide some examples regarding how to parse User object?

**Comment by sbertix** [comment]
@Goktug, check out [`User`](https://github.com/sbertix/Swiftagram/blob/development/Sources/Swiftagram/Responses/User.swift) references in the `development` branch, for an idea on how to parse this all 💪
