### ISSUE TITLE
Credentials expiring

### ISSUE THREAD

**Issue by joshuazmiller** [sbertix/Swiftagram#262]
- [x] I've searched past issues and I couldn't find reference to this. 

**Swiftagram version**
5.4.0

**Describe the bug**
After a couple days the Instagram login expires.

**To reproduce**
1. Login using Swiftagram.
2. Wait a couple days (as little as 1 to 2 days).
3. User credentials stop working for all IG requests.
4. Logging out and back in resolves for another day or two.

**Expected behavior**
Credentials continue working without logging out and back in.

**Device and system**
iPhone 13, iOS 15.0.2

**Comment by sbertix** [comment]
Hey @joshuazmiller, 

I've looked into this a bit more and turns out the endpoints are returning a 500 error code, with no additional explanation. 
The response header is indeed different, though, so I'm worried it might be related to broader changes Instagram-side. 
I was only able to replicate this (for now) with the web based authentication, but I'm now also trying the basic one, and I'll update this conversation when I know more about it.

**Comment by MariaJsn** [comment]
Hi @sbertix 
is there any news? I am facing this problem too.
Do you have any advice for solving the problem, albeit temporarily?

Thanks,
Maria

**Comment by joshuazmiller** [comment]
Some parallel issues opened in other repos the past few weeks:

Noted the issue but haven't solved:
https://github.com/meetfranz/franz/issues/2107
https://github.com/meetfranz/franz/issues/2112

Possible solution but a bit unlikely:
https://github.com/penpot/penpot-docs/pull/48
> Every now and then, Instagram shows an error when opening a profile page without a / at the end ("Oops, an error occurred. ").

So perhaps adding a `/` could fix? I don't really think it would, but who knows.

Here is an interesting recent discussion as well:
https://github.com/getferdi/ferdi/issues/2185

> It looks like the `signal_flush_timestamp` cookie might be involved in the once-per-day aspect of this issue.
> ...
> I found that removing all the cookies in the service tools window, then reloading the service put me right back into a working state. At least until the next time it happened.

Based on the final comments on that thread, maybe removing (certain) cookies solves?

**Comment by yusuftor** [comment]
Hi, any update on this? Is this still an issue? Thanks!

**Comment by sbertix** [comment]
Hey @joshuazmiller, @MariaJsn and @yusuftor,

Sorry for the long wait 😢 
I guess this might have been an iOS "bug" (something similar would happen with logging inside the Twitter app), cause I'm not able to replicate this anymore.
