### ISSUE TITLE
Rate limits

### ISSUE THREAD

**Issue by yusuftor** [sbertix/Swiftagram#278]
Does anyone know the rate limits for pagination? This isn't actually a bug, just a general question! Can't seem to remove the label, sorry about that.

**Comment by sbertix** [comment]
Hey @yusuftor, 

Sorry for the late reply. 
Instagram does not appear to use a single threshold for rate limiting calls, but it's depending, instead, on the logged in account behavior. 

That said, some endpoints (e.g. followers and following, or ones that are not related directly to the logged in user) should be called with an added level of caution. 

_No worries for the `bug` label. Next time, make sure to use the **Discussions** page of the repo next time you're looking for help, please._
