### ISSUE TITLE
Is it possible to get display url and comments?

### ISSUE THREAD

**Issue by mobiledevgiant** [sbertix/Swiftagram#284]
I am using this framework on my application.
Is it possible to get display url and all comments of this post?

https://www.instagram.com/p/CY6dfn4oks5/?utm_source=ig_web_button_share_sheet

If yes, can you please share codes for it?
Thanks.
Vasyl.

**Comment by 89z** [comment]
I have an alternate framework for this purpose:

~~~go
package main
import "github.com/89z/mech/instagram"

func main() {
   log, err := instagram.NewLogin("USERNAME", "PASSWORD")
   if err != nil {
      panic(err)
   }
   med, err := log.Media("CY6dfn4oks5")
   if err != nil {
      panic(err)
   }
   println(med.Display_URL)
   for _, edge := range med.Edge_Media_To_Parent_Comment.Edges {
      println(edge.Node.Text)
   }
}
~~~

https://github.com/89z/mech

**Comment by mobiledevgiant** [comment]
> I have an alternate framework for this purpose:
> 
> ```go
> package main
> import "github.com/89z/mech/instagram"
> 
> func main() {
>    login, err := instagram.NewLogin("USERNAME", "PASSWORD")
>    if err != nil {
>       panic(err)
>    }
>    media, err := login.Media("CY6dfn4oks5")
>    if err != nil {
>       panic(err)
>    }
>    println(media.Display_URL)
>    for _, edge := range media.Edge_Media_To_Parent_Comment.Edges {
>       println(edge.Node.Text)
>    }
> }
> ```
> 
> https://github.com/89z/mech

@89z 
Thank you for your quick help.
Is there any Objective-c or Swift codes for this? 

Regards
Vasyl

**Comment by sbertix** [comment]
Hey @vasylboy90,

**Swiftagram** is a Swift client for the Instagram Private API, meaning you need to log in and then find the media you're referring to within the API. 
Once you have that, let's call `identifier`, you can then access all comments by using `Endpoint.Media.Posts.comments(for:startingAt:)`, and all media-related info by calling `Endpoint.Media.summary(for:)`. 

_Also, please make sure to use the **Discussions** page of the repo next time you're looking for help._
