### ISSUE TITLE
How can I get full stories info from highlights?

### ISSUE THREAD

**Issue by germ1nand0** [sbertix/Swiftagram#285]
### Discussed in https://github.com/sbertix/Swiftagram/discussions/283

<div type='discussions-op-text'>

<sup>Originally posted by **germ1nand0** January 20, 2022</sup>
How can I get full stories info from highlights?
I get preview of highlights by Swiftagram.Endpoint.user(userID).higlights.
Response contains only cover media(no info about stories in this higlight except lastMediaId) and the identifier
I Try to send this identifier to static func stories<C: Collection>(_ identifiers: C) to get information about stories but don't get what I want</div>

**Comment by 89z** [comment]
please provide example URL

**Comment by sbertix** [comment]
Hey @germ1nand0,

Sorry for the late reply 😢 
You would need to call `Endpoint.Media.Stories.owned(by: ["highlight:XXXXXX"])` passing the identifier of the highlight tray item you received in place of `highlight:XXXXXX`. Unfortunately this endpoint is a bit of a hit or miss and right now it appears to return some error. 
I'll try and fix it for `6.0.0`. 

_Also, please make sure to use the **Discussions** page of the repo next time you're looking for help._
