### ISSUE TITLE
Get Medias

### ISSUE THREAD

**Issue by MariaJsn** [sbertix/Swiftagram#29]
I am trying to get user own medias. But I can not return any data.
My codes:
      
```
  let task = Endpoint.Feed.posts(by: secret.identifier)
        .unlocking(with: secret)
        .publish()
        .prefix(3)
        .map{
            $0.medias
                .array()?
                .compactMap {_ in
                    
                    //will fill after getting data
                    return Media(id: "", name: "")
                } ?? []
            
        }
        .catch { error -> Empty<[Media], Never> in
            print(error);
            return Empty() }
        .assign(to: \.appendMedias, on: self)
```

How can I fix it?
Thanks,
Maria

**Comment by sbertix** [comment]
Hey 😊 \

I feel like this might be an error with your **Combine** logic: `task`, in your case, is an instance of `AnyCancellable`, but it's not strongly referenced anywhere, so it will be released at the end of the current cycle.\

Try something like this instead, meaning your subscription will not be disposed until the instance release, allowing it to actually run.

```swift
/// This should be a property of your model instance, or something similar.
var taskCancellable: AnyCancellable?
/// Append medias.
var appendMedias: [Media] { 
   get { ... } 
   set { ... } 
}

/// The function you're calling to update media.
func updateMedia() {
   taskCancellable = Endpoint.Feed.posts(...)
}
```

**Comment by egasteam** [comment]
Thanks for your help :)
I have one more question. How can I store secret after login? And open app next time how can I use this secret to login?

**Comment by MariaJsn** [comment]
You are awesome. Thank you very much.
So how can I store secret after login? And open app next time how can I use this secret to login?

**Comment by MariaJsn** [comment]
Thanks for your help :)
I have one more question. Is there any event to understand task is finish?
