### ISSUE TITLE
how can i get video from instagram stories url using Swiftagram?

### ISSUE THREAD

**Issue by olegjunios** [sbertix/Swiftagram#292]

**Comment by 89z** [comment]
please provide example URL

**Comment by olegjunios** [comment]
this is my code 


`self.completion = { [weak self] result in
            print(result)
            guard let self = self else { return }
            guard let userName = self.userName else {
                self.dismiss(animated: true)
                return }
            guard let storyId = self.storyId else { return }
            guard let link = self.link else { return }
            
            self.secret = result/* the authentication response */
            
            print(userName, storyId, link, self.secret as Any, self.bin.count)
            guard let secret = self.secret else { return }
            
                Endpoint.recent.stories
                    .unlock(with: secret)
                    .session(.instagram)
                    .sink { uu in
                        print(uu)
                    } receiveValue: { oo in
                        print(oo) // <------- i don't get result 
                    }
                    .store(in: &self.bin)
        }`

**Comment by 89z** [comment]
please provide example URL

**Comment by olegjunios** [comment]
what did you mean "example url"?
url from instagram stories?

**Comment by 89z** [comment]
If you dont know what a URL is, you probably shouldnt be using this package.

**Comment by olegjunios** [comment]
look, i'm trying get media from copied instagram stories
early i used SwiftyInsta but now is not supported
this is my code where i get recent stories but is not what I need
<img width="909" alt="Снимок экрана 2022-03-07 в 20 26 05" src="https://user-images.githubusercontent.com/94039262/157095028-aad57e83-4c88-4829-85ea-53b22b814f60.png">

<img width="1159" alt="Снимок экрана 2022-03-07 в 20 28 32" src="https://user-images.githubusercontent.com/94039262/157095408-04ecf6c0-1f14-4356-9dc4-567385186a1f.png">

if you know how do this can you help me do this, please?

**Comment by olegjunios** [comment]
https://www.instagram.com/stories/highlights/17939011231603196/
https://www.instagram.com/stories/alytvyk/2788645701447767756/

**Comment by olegjunios** [comment]
where i can get example URL what you need?

**Comment by sbertix** [comment]
Hey @olegjunios, 

**Swiftagram** is a client for Instagram Private API. Reading stories and highlights URLs is not supported, and won't be, cause it's outside the scopes of this. 

Let me know if I misunderstood the request, though. 

_Also, please make sure to use the **Discussions** page of the repo next time you're looking for help._
