### ISSUE TITLE
error when trying to get media from a copied link from a private account

### ISSUE THREAD

**Issue by olegjunios** [sbertix/Swiftagram#294]
if i try paste link from public account - function worked (public account url: https://www.instagram.com/p/CZ1X_PVorS4/ )
if i paste link from private account - i getting this error: (private account url: https://www.instagram.com/p/CXdy1B-oDnSqOYMQ5fGdSgsHOBwzsdUehXouis0/)

maybe it happened after a different number of characters after "p/"

how i can fix it? have any ideas?

<img width="1274" alt="Снимок экрана 2022-03-11 в 10 30 53" src="https://user-images.githubusercontent.com/94039262/157830949-3d8fe3ca-b941-41bf-9f81-b92e6afe542e.png">

**Comment by sbertix** [comment]
Hey @olegjunios, 

Sorry for the late reply. 
Unfortunately I haven't really found a work around for this, so I'm planning on removing this method from `6.0.0`, being, also, strictly speaking not part of the Instagram Private API (it's more of an accessory).
