### ISSUE TITLE
Visual Login issue

### ISSUE THREAD

**Issue by ramimoghrabi** [sbertix/Swiftagram#297]
- [x] I've searched past issues and I couldn't find reference to this. 

version 6.0.0

While using the visual login method as stated in the example and as below : 

Authenticator.transient
                    .visual(filling: self.view)
                    .authenticate()
                    .prepare(with: .combine(session: .ephemeral))
                    .sink(receiveCompletion: { _ in self.dismiss(animated: true, completion: nil) },
                          receiveValue: completion)
                    .store(in: &self.bin)

i receive error : 

Could not cast value of type 'Requests.Receivables.FlatMap<Requests.Receivables.Switch<Requests.Receivables.Switch<Requests.Receivables.Future<Requests.URLSessionCombineRequester, ()>, Requests.Receivables.Future<Requests.URLSessionCombineRequester, Swiftagram.AuthenticatorWebView<Requests.URLSessionCombineRequester>>>, Requests.Receivables.Future<Requests.URLSessionCombineRequester, Swiftagram.Secret>>, Swiftagram.Secret>' (0x11510f8e8) to 'Requests.URLSessionCombineMockReceivable' (0x11510f9c8).

tested on iphone 12 pro max iOS 15.4

**Comment by sbertix** [comment]
Hey @ramimoghrabi, 

Sorry for the late reply. 
`6.0.0` was never production ready. I had planned to release it back this Spring, but never ended up to, and I'm now in the process of rewriting it entirely (meaning the code in the _6.0.0_ branch will be basically scrapped). 
Hopefully a "new `6.0.0`" can be ready by the holidays. 
I'm closing the issue as it's not about an actual release, or `main`, but just some WIP.
