### ISSUE TITLE
Endpoint.user("user_identifier").follow() doesn't work

### ISSUE THREAD

**Issue by galblank** [sbertix/Swiftagram#301]
- [ ] I've searched past issues and I couldn't find reference to this. 

**Swiftagram version**
latest

**Describe the bug**
After getting user's secret and trying to call the following API, nothing actually happens and the user is not beginning to follow the user provided in the "user_identifier"
Endpoint.user("user_identifier").follow() doesn't work

**To reproduce**
Endpoint.user(secret.identifier)
                                        .summary
                                        .unlock(with: secret)
                                        .session(.instagram)
                                        .sink(receiveCompletion: { subscriber in
                                            debugPrint(subscriber)
                                        }, receiveValue: { user in
                                            guard let user = user.user else { return }
                                          Endpoint.user("userB").follow() 
                                        })
                                        .store(in: &CacheManager.sharedInstance.bin)

            }
        }
    }

**Expected behavior**
User A starts Following User B

**Additional context**

**Device and system**
iPhone Simulator 15

**Comment by sbertix** [comment]
Hey @galblank. 
Sorry for the super late reply. 

There appears to be an error in your code. The first `summary` call is unneeded and then you're not flat mapping the `Publisher` to wait for `follower` to return. You can do something like: 

```swift
Endpoint.user("userB")
   .follow()
   .unlock(with: secret)
   .session(.instagram)
   .sink { _ in } receiveValue: { _ in }
   .store(in: &CacheManager.sharedInstance.bin)
```

Or flat mapping the result if you're doing something sooner with `summary`: 

```swift
Endpoint.user("userB")
   .summary
   .unlock(with: secret)
   .session(.instagram)
   .flatMap { _ in 
      Endpoint.user("userB")
         .follow()
        .unlock(with: secret)
        .session(.instagram)
   }
   .sink { _ in } receiveValue: { _ in }
   .store(in: &CacheManager.sharedInstance.bin)

```
