### ISSUE TITLE
Swift Concurrency API

### ISSUE THREAD

**Issue by mycroftcanner** [sbertix/Swiftagram#304]
Do you have any plan to implement a Swift Concurrency API?  

Using combine feels so cumbersome now.

**Comment by sbertix** [comment]
Hey @mycroftcanner, sorry for the late reply. 
Theoretically there is a beta setup, on another branch, with `ComposableRequest` 6 that works with structured concurrency. However, I had to stop working on this for some personal issues and I never completed the web-based authentication for it. 

I might try and come back to it in the near future, but ETA. Sorry
