### ISSUE TITLE
Crash at 6.0.0 Build

### ISSUE THREAD

**Issue by AhmedShammala** [sbertix/Swiftagram#307]
- [x] I've searched past issues and I couldn't find reference to this.

**6.0.0**
Crash once I click to show the LoginView 

Crash message :
'Requests.Receivables.FlatMap<Requests.Receivables.Switch<Requests.Receivables.Switch<Requests.Receivables.Future<Requests.URLSessionCombineRequester, ()>, Requests.Receivables.Future<Requests.URLSessionCombineRequester, Swiftagram.AuthenticatorWebView<Requests.URLSessionCombineRequester>>>, Requests.Receivables.Future<Requests.URLSessionCombineRequester, Swiftagram.Secret>>, Swiftagram.Secret>' (0x1ff7409a0) to'Requests.URLSessionCombineMockReceivable' 

my Login View code 
<img width="804" alt="image" src="https://user-images.githubusercontent.com/11911318/201540263-e4dc9b09-878c-44b2-9191-d5c4dae7e293.png">

Any help ?

Thanks

**Comment by sbertix** [comment]
Hey @AhmedShammala, 

Sorry for the late reply. 
The code in the `6.0.0` branch was never intended to be production ready, I simply had to pause development before completing it. 
Unfortunately I'm only fixing bugs in production, especially as I'm working on actually releasing a "new `6.0.0`" as we speak, so the code in `6.0.0` will be basically scrapped.
