### ISSUE TITLE
Could not connect to the server.

### ISSUE THREAD

**Issue by VitaliiDeveloper** [sbertix/Swiftagram#316]
- [x] I've searched past issues and I couldn't find reference to this.

**Swiftagram version**
5.4.0

**Describe the bug**
After login trying make requests on User/Followers/Following and get strange issue:

`Task <7935F623-530F-448D-960B-6B0C5825F1F0>.<15> finished with error [-1004] Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={_kCFStreamErrorCodeKey=61, NSUnderlyingError=0x2815588d0 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "(null)" UserInfo={_NSURLErrorNWPathKey=satisfied (Path is satisfied), viable, interface: lo0, _kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <7935F623-530F-448D-960B-6B0C5825F1F0>.<15>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <7935F623-530F-448D-960B-6B0C5825F1F0>.<15>"
), NSLocalizedDescription=Could not connect to the server., NSErrorFailingURLStringKey=https://[0000:0000:0000:0000:0000:0000:0000:0001]:8872/api/v1/friendships/10957/followers/?max_id=QVFEYUZGQVJvaU5kWE1sajBlUnY3bXBHcXBpSHctUjFQRGJWMXJ0Qjd4eHNiaW9XXzl0WWlPYlRfd0s1V244d0JxajBLVlJTVHFwbG1OS1FnWjRPU2RVOQ%3D%3D, NSErrorFailingURLKey=https://[0000:0000:0000:0000:0000:0000:0000:0001]:8872/api/v1/friendships/10957/followers/?max_id=QVFEYUZGQVJvaU5kWE1sajBlUnY3bXBHcXBpSHctUjFQRGJWMXJ0Qjd4eHNiaW9XXzl0WWlPYlRfd0s1V244d0JxajBLVlJTVHFwbG1OS1FnWjRPU2RVOQ%3D%3D, _kCFStreamErrorDomainKey=1}`

(UserID it just for example)

**To reproduce**
1. Make authorization with visual form
2. Make in one to one stack request to user -> followers -> following

**Device and system**
iPhone 13 PRO 15.6

**Comment by sbertix** [comment]
Hey Vitalii, 
Sorry but I'm just seeing this. Does this still happen? It look like it might be just an internet connection issue, so I'm closing this issue.
