### ISSUE TITLE
How can i get profile photo url ?

### ISSUE THREAD

**Issue by aslios** [sbertix/Swiftagram#32]
Hi Sbertix,
I try to get profile photo url from userdata like this but i cant get url;
             

>        _let image = $0.imageVersions2.candidates.array()?.first
>                     let imageUrl = image!.url
>                     print(imageUrl)_

But when i try to this code i can get,
_

> let a = image!["url"].value

_

Can you show me correct programmability way how can i get url ?
thank you

**Comment by sbertix** [comment]
Hey @aslios

I'm not 100% positive on what you mean by "profile photo url", cause it seems to suggest you are maybe looking for the user's avatar, but then refer to their actual posts, so I'm just gonna try and explain both. 😊 

### Posts
```swift
Endpoint.Feed.posts(by: …)
    .unlocking(with: …)
    .task(maxLength: 1) {
        // I'm just using the first element as an example.
        guard let item = try? $0.get().items[0] else { return }
        let previewURL: URL?
        switch item.mediaType.int() {
        case 8?:
            // A carousel (aka an album).
            previewURL = item.carouselMedia[0].imageVersions2.candidates[0]["url"].url()
        default:
            // A video or picture.
            previewURL = item.imageVersions2.candidates[0]["url"].url()
        }
        // Do something with `previewURL`.
        print(previewURL as Any)
    }
    .resume()
```

I'm aware this is not convenient at all, and in the next update (coming before the end of the week) you will be able to obtain it directly without needing to know the actual structure in advance.

```swift
/* Given `item` as above, It will be something as simple as… */
item.preview
```

### Avatar
```swift
Endpoint.User.summary(for: …)
    .unlocking(with: …)
    .task {
        print((try? $0.get().user.profilePicUrl.url()) as Any)
    }
    .resume()
```

**Comment by aslios** [comment]
thank you so much :)
