### ISSUE TITLE
User name and full name from secret key

### ISSUE THREAD

**Issue by MariaJsn** [sbertix/Swiftagram#33]
I can find user identifier in secret likse secret.identitfier.
Is there any option to get user name and full name in secret?

Thanks,
Maria

**Comment by sbertix** [comment]
No unfortunately there's no such feature.\
You have to call `Endpoint.User.summary(for: secret.identifier)` in order to retrieve user info. 

I might consider adding it though, it might be useful 💪

**Comment by sbertix** [comment]
I've thought about this a lot and I came to the conclusion that it's definitely a feature that it's not worth implementing: too many drawbacks.\
For starters, `Secret` is always passed as read-only to all `.locking()` concrete implementations, so there's no way to update it consistently and syncing it to the correct `Storage`, as it's 100% `Storage` agnostic right now (as it should be, imho).\
Plus username, name, thumbnail, etc. can change way too often for this to be a viable idea.\
I feel like the current scenario (getting a `Secret` and then calling `Endpoint.User.summary(for: secret.identifier)`, is still the better one of the two.

This was planned for `3.0.0`, but it has now been scrapped.
Sorry @MariaJsn
