### ISSUE TITLE
Follow and Unfollow doesn't work

### ISSUE THREAD

**Issue by aslios** [sbertix/Swiftagram#34]
Hi Sbertix,
i am using that code for follow and unfollow but they are not working.Can u help?

 
-Unfollow
> Endpoint.Friendship.unfollow(String(userPk))
>         .unlocking(with: secret)
>         .task {
.......
> }

 -Follow
>  Endpoint.Friendship.follow(String(userPk))
>         .unlocking(with: secret)
>         .task {
.......
> }

**Comment by sbertix** [comment]
Hey 💪\
Yep. I'm aware of this, and it's due to a change in the signing code of the request.\
I'm fixing it ASAP
