### ISSUE TITLE
How can i get posts which i'm tagged in?

### ISSUE THREAD

**Issue by aslios** [sbertix/Swiftagram#35]
Hi Sbertix :)
i cannot get post  which i'm tagged in, i am using this endpoint is it true ?
_

> Endpoint.Feed.tagged(with: secret.identifier)
>         .unlocking(with: secret)
>             .task(maxLength: .max,

_

**Comment by sbertix** [comment]
The endpoint you're using is to return actual pics tagged with "#tags #like #this".\
Use `Endpoint.Feed.posts(including:)` for user tags 💪
