### ISSUE TITLE
"useragent mismatch" error

### ISSUE THREAD

**Issue by Goktug** [sbertix/Swiftagram#41]
I think version `2.2.0` might broke something because all APIs are giving this response:

`{
  "message": "useragent mismatch",
  "status": "fail"
}`

**Comment by sbertix** [comment]
`Secret`s from `2.1.*` are not compatible with `2.2.0`.

**Comment by Goktug** [comment]
Still not working. Even I deleted the app and then install it again.

My request header like this and I am trying to send a request from the simulator.

```
Host: i.instagram.com
X-FB-HTTP-Engine: Liger
X-Pigeon-Rawclienttime: 1593455538.000
X-IG-Bandwidth-Speed-KBPS: -1.000
User-Agent: 121.0.0.29.119
X-IG-Bandwidth-TotalTime-MS: 0
X-IG-App-Locale: en_US
X-IG-Extended-CDN-Thumbnail-Cache-Busting-Value: 1000
Cookie: ----- SECRET ----
X-IG-App-ID: 567067343352427
X-Ads-Opt-Out: 0
X-MID: XvozqAABAAGDg-8AAxViu0BJTxUd
X-IG-Android-ID: android-39404bfd53d14772
X-IG-Bandwidth-TotalBytes-B: 0
X-IG-Capabilities: 3brTvwE=
X-IG-Connection-Type: WIFI
X-Bloks-Version-Id: 1b030ce63a06c25f3e4de6aaaf6802fe1e76401bc5ab6e5fb85ed6c2d333e0c7
X-Pigeon-Session-Id: a83f6478-69b6-41da-8d99-306078385347
X-IG-Connection-Speed: 1301kbps
Connection: close
X-IG-WWW-Claim: 0
X-Bloks-Is-Layout-RTL: false
Accept-Language: en-US
X-IG-Device-ID: 39404BFD-53D1-4772-A366-9578A3312F30
X-CM-Latency: -1.000
X-CM-Bandwidth-KBPS: -1.000
Accept-Encoding: gzip
X-IG-Device-Locale: en_US
Accept: */*
```

**Comment by sbertix** [comment]
Totally messed it up.\
Apparently I must have messed something up in the commit process, cause I was super positive I fixed that.

I know it should be avoided, but I'm re-releasing `2.2.0`, hoping this was caught soon enough.\
Thank you, man.

**Comment by Goktug** [comment]
It is working now. Thank you, man!
