### ISSUE TITLE
Recent activities

### ISSUE THREAD

**Issue by aslios** [sbertix/Swiftagram#43]
Hi Sbertix :) 
How can i get recent activities? for example

>  - somebody likes your photo...
>  - somebody comment your photo...
>  - somebody follow you..

I couldnt find endpoint about this :/ can u help me please ?

**Comment by sbertix** [comment]
It's not yet a feature unfortunately.\
As the library it's getting more in its functionality, though, I'm definitely gonna expand all available endpoints, starting with the next release, that I hope to publish by the end of the week 💪
@aslios 

I'll close this issue, once it's added.
