### ISSUE TITLE
Use Swiftagram without swiftUI.

### ISSUE THREAD

**Issue by BoikoArtem30091994** [sbertix/Swiftagram#48]
- [x] I've searched past issues and I couldn't find reference to this. 
- [x] I've checked out all provided _Examples_.

**Info**  
Write your question or whatever you need, related to **Swiftagram**.

Hello. Can't embed swiftagram usage in UIKit. Should the library work not in swift ui or is it not available at the moment?

**Comment by sbertix** [comment]
Of course you can use it with `UIKit` 😊.

You can rely on `LoginViewController` from the Followers example, or just build your own custom one.

```swift
class LoginViewController: UIViewController {
    /// The completion handler.
    var completion: ((Secret) -> Void)?
    /// The web view.
    var webView: WKWebView? {
        didSet {
            guard let webView = webView else { return }
            webView.frame = view.frame
            view.addSubview(webView)
        }
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        // Authenticate.
        WebViewAuthenticator(storage: KeychainStorage()) { self.webView = $0 }
            .authenticate { [weak self] in
                switch $0 {
                case .failure(let error): print(error.localizedDescription)
                case .success(let secret):
                    self?.completion?(secret)
                    self?.dismiss(animated: true, completion: nil)
                }
            }
    }
}
```

**Comment by BoikoArtem30091994** [comment]
I try this code to implement in my project. But WKWebView does not load Instagram login, you can try to create the project and set up your own login. It's not working

**Comment by sbertix** [comment]
What version of Xcode are you on?\
What Swift toolchain version are you using?\
Cause I feel like that might be the issue there, since it does work on my part 🥺

**Comment by BoikoArtem30091994** [comment]
Xcode 11.5. It seems to me that the problem is in the WebViewAuthenticator, because at first I built my project with UIkit and an example from Followers, and it does not work, and then using swift UI everything is fine. 
No mistake just white WKWebView. If I simply create a request with example url, then everything works fine, that is the problem is not in wkwebview.

**Comment by BoikoArtem30091994** [comment]
Simple example implementation

import UIKit
import WebKit
import Swiftagram
import SwiftagramCrypto

class ViewController: UIViewController {

    var webView: WKWebView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        webView = WKWebView(frame: .zero)
        self.view.addSubview(webView)
        webView.translatesAutoresizingMaskIntoConstraints = false
        
        NSLayoutConstraint.activate([
            webView.leadingAnchor.constraint(equalTo: self.view.leadingAnchor, constant: 0),
            webView.trailingAnchor.constraint(equalTo: self.view.trailingAnchor, constant: 0),
            webView.topAnchor.constraint(equalTo: self.view.topAnchor, constant: 0),
            webView.bottomAnchor.constraint(equalTo: self.view.bottomAnchor, constant: 0)
        ])
        
        // This request work fine
        
//        let url = URL(string: "https://www.instagram.com/accounts/login/")!
//        let request = URLRequest(url: url)
//        webView.load(request)
//
        
        // WebViewAuthenticator not load request
        
        WebViewAuthenticator(storage: KeychainStorage()) { self.webView = $0 }
        .authenticate { [weak self] in
            switch $0 {
            case .failure(let error): print(error.localizedDescription)
            case .success(let secret):
                print(secret)
//                self?.completion?(secret)
                self?.dismiss(animated: true, completion: nil)
            }
        }
    }
}

**Comment by BoikoArtem30091994** [comment]
Simple example implementation
`
import UIKit
import WebKit
import Swiftagram
import SwiftagramCrypto

class ViewController: UIViewController {

    var webView: WKWebView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        webView = WKWebView(frame: .zero)
        self.view.addSubview(webView)
        webView.translatesAutoresizingMaskIntoConstraints = false
        
        NSLayoutConstraint.activate([
            webView.leadingAnchor.constraint(equalTo: self.view.leadingAnchor, constant: 0),
            webView.trailingAnchor.constraint(equalTo: self.view.trailingAnchor, constant: 0),
            webView.topAnchor.constraint(equalTo: self.view.topAnchor, constant: 0),
            webView.bottomAnchor.constraint(equalTo: self.view.bottomAnchor, constant: 0)
        ])
        
        // This request work fine
        
//        let url = URL(string: "https://www.instagram.com/accounts/login/")!
//        let request = URLRequest(url: url)
//        webView.load(request)
//
        
        // WebViewAuthenticator not load request
        
        WebViewAuthenticator(storage: KeychainStorage()) { self.webView = $0 }
        .authenticate { [weak self] in
            switch $0 {
            case .failure(let error): print(error.localizedDescription)
            case .success(let secret):
                print(secret)
//                self?.completion?(secret)
                self?.dismiss(animated: true, completion: nil)
            }
        }
    }
}

`

**Comment by sbertix** [comment]
I wrote a new UIKit project, added a `LoginViewController` like I defined it above, and tested it in the simulator, and it still works for me 😢 
I'll check your code above to see if there's something missing there.

<br />
<img width="961" alt="image" src="https://user-images.githubusercontent.com/1803415/87761609-0bbb1d00-c812-11ea-8467-23d7242ef827.png">

**Comment by sbertix** [comment]
I removed it by mistake @BoikoArtem30091994 😢 do you mind reposting it? Apologies

**Comment by BoikoArtem30091994** [comment]
> I wrote a new UIKit project, added a `LoginViewController` like I defined it above, and tested it in the simulator, and it still works for me 😢
> I'll check your code above to see if there's something missing there.
> 
> 
> <img alt="image" width="961" src="https://user-images.githubusercontent.com/1803415/87761609-0bbb1d00-c812-11ea-8467-23d7242ef827.png">

My implementation slightly different. I will try according to your option. Thank you for your quick answer. I will give feedback.
<img width="785" alt="Screenshot 2020-07-17 at 10 46 27" src="https://user-images.githubusercontent.com/31438215/87761918-eda5ea80-c81a-11ea-914c-d536daa41a5d.png">

**Comment by BoikoArtem30091994** [comment]
It's working. Thank you for your support.

**Comment by sbertix** [comment]
When you reassigning the `WKWebView` in row 41, you're not adding the new one in the view hierarchy, so it won't show.\
Basically everything between 21 and 40 is useless cause it's scrapped once you assign a new `webView` in 41.

I'll add auto layout constraints to `LoginViewController` example in Followers, so people can just copy and paste it, for now you can just do:

```swift
import UIKit
import WebKit

import Swiftagram
import SwiftagramCrypto

class LoginViewController: UIViewController {
    /// The completion handler.
    var completion: ((Secret) -> Void)?
    /// The web view.
    var webView: WKWebView? {
        didSet {
            guard let webView = webView else { return }
            webView.frame = view.frame
            view.addSubview(webView)
            // Add constraints.
            NSLayoutConstraint.activate([
                webView.topAnchor.constraint(equalTo: webView.topAnchor),
                webView.leadingAnchor.constraint(equalTo: webView.leadingAnchor),
                webView.trailingAnchor.constraint(equalTo: webView.trailingAnchor),
                webView.bottomAnchor.constraint(equalTo: webView.bottomAnchor)
            ])
        }
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        // Authenticate.
        WebViewAuthenticator(storage: KeychainStorage()) { self.webView = $0 }
            .authenticate { [weak self] in
                switch $0 {
                case .failure(let error): print(error.localizedDescription)
                case .success(let secret):
                    self?.completion?(secret)
                    self?.dismiss(animated: true, completion: nil)
                }
            }
    }
}
```
