### ISSUE TITLE
Story Viewers

### ISSUE THREAD

**Issue by MariaJsn** [sbertix/Swiftagram#50]
I could not find story viewers endpoint. When I get stories, I can get only 5 viewers not all.
Is there any story viewers end point?

**Comment by sbertix** [comment]
Hey 😊\
You're right, there's not. Totally a big oversight, I'm adding it ASAP.\
Thank you 💪 @MariaJsn

**Comment by sbertix** [comment]
_If you found this useful, please consider starring :star: this repo, or even [sponsoring it](https://paypal.me/sbertix) :dollar:.<br />Even just $1 can help me maintain this._<br />_Thank you for using **Swiftagram**._

**Comment by sbertix** [comment]
I've added it in the last update (apologies for the auto-comment above).\
`Endpoint.Media.Stories.viewers(for:startingAt:)`
