### ISSUE TITLE
Migrate from Android API to iOS API

### ISSUE THREAD

**Issue by MatoMA** [sbertix/Swiftagram#54]
- [x] I've searched past issues and I couldn't find reference to this. 

**Is your feature request related to a problem? Please describe.**

When an iOS user logs in with Swiftagram, he/she will receive a security alert email: logging in with an XianMi Android device. This gives an impression of account-being-hacked.
In some cases, Instagram will restrict login on an unknown device in a totally different platform. In our test, even after clicking the "That's me" button on Instagram, the login of accounts without 2FA was fail. After changing the user agent to iOS, the login succeeded.

**Describe the solution you'd like**

Please add support of iOS apiUserAgent(or device).

**Additional context**

The form of iOS user agent likes this:
Instagram 123.1.0.26.115 (iPhone9,1; iOS 13_3; en_US; en-US; scale=2.00; 750x1334; 190542906)

Ref: https://developers.whatismybrowser.com/useragents/explore/software_name/instagram/

**Comment by sbertix** [comment]
Custom user agents are already supported in `WebViewAuthenticator`, unfortunately, as the user agent won't match the one used by the API app, which needs to be an Android device, all encrypted endpoints won't work (everything else should be fine, though).

I might try and figure out whether all endpoints still work using Instagram iOS app API (i.e. simply adjusting the user agent), but especially regarding `BasicAuthenticator`, there's no literature on it, and I can't promise I can make it work (cause I'm pretty sure they'd use a different encoding + authentication flow).

**Comment by MatoMA** [comment]
The form of deviceIdentifier likes this (if it still works):
    let hashedGuid = guid.uuidString.MD5
    return "iOS-\(hashedGuid.prefix(16))"

**Comment by mycroftcanner** [comment]
What's the status? Do you need any help?

**Comment by sbertix** [comment]
Hey @mycroftcanner.\
I haven't actually started working on this: it's definitely planned for `4.1.0`, but it's gonna be the last thing I work on before release, as I feel like it's not as important as everything else.\
If you feel like forking the repo and testing some iOS user agents and devices on the `development` branch code (I'm mostly worried about `BasicAuthenticator`), feel free: it'd be a great help 💪

**Comment by sbertix** [comment]
Since I ended up adding stories and video posts upload in `4.1.0`, I'm moving this to a future release, so I have more time to perfect it. Just fyi.

**Comment by sbertix** [comment]
I've tried several implementations to make all features work with the iPhone API, but, especially for authentication, it's way beyond the scopes of this project, and the time I can dedicate to it. 
Apologies.

**Comment by sbertix** [comment]
Hey @MatoMA and @mycroftcanner  💪 

I've added support for iOS user agents in the `development` branch, and the release is planned for `4.2.0`. 
I've tested it a bit and it all seems fine. Do you mind checking if it works for you too and satisfies your needs with the implementation? 

Keep in mind the default device is still an Android phone, so in order to use an iOS once instead, you need to add the code below when your app starts. 

```swift
#If canImport(UIKit)
// If you're on an iPhone or on an iPhone simulator you can do…
Client.default = .current ?? .iPhone11ProMax
#else
// … otherwise
Client.default = .iPhone11ProMax
#endif
```

**Comment by joshuazmiller** [comment]
Hi @sbertix 

I just tested it on a device [iPhone X] and got this error.

<img width="957" alt="Screen Shot 2020-10-27 at 1 03 49 PM" src="https://user-images.githubusercontent.com/20162542/97356070-f6b04a00-1854-11eb-8170-0f3afb70e39a.png">

It works with `.iPhone11ProMax` but not with `.current`

Also, will the update to support iOS 12 causing all users to be logged out? Tbh there's not many people on iOS 12, but having all users log-in again is a pretty big deal I think. Is there a way to not require re-logging in if we update the package?

Thanks.

**Comment by sbertix** [comment]
Hey @joshuazmiller, yep, `.current` indeed requires more testing. I've already fixed the code and I'll probably push it tomorrow :muscle: 

If you're referring to the previous update about iOS 12 compatibility, the only real difference is in `Storage` so _theoretically_ you should be able to access it using legacy keychain setups. 
As for this new update, I'm totally planning on reusing previously stored `Secret`s, it's just not live as of yet. 
I even **might** try and support previous implementation so no logging out for people that are stuck on older versions (pre `Secret`s wipe, let's say).
