### ISSUE TITLE
2FA on iOS Simulator

### ISSUE THREAD

**Issue by senolatac** [sbertix/Swiftagram#63]
- [x] I've searched past issues and I couldn't find reference to this. 

**Swiftagram version**
3.1.1

**Describe the bug**
Two Factor Verification was tried with your example project on ios simulator then error message was taken like:
**We couldn't connect to Instagram. Make sure you're connected o the internet and try again.**

**To reproduce**
1. Run Example project on ios Simulator.
2. Then try to login with Two Factor Verification enabled instagram account.

**Expected behavior**
To display Two Factor Verification code.

**Additional context**
-

**Device and system**
iPhone Simulator 13.6

**Comment by sbertix** [comment]
Hey @senolatac 💪\
Do you have any more info to actually replicate this?\
Cause that's a weirdly specific error message, and it seems like it's not related to **Swiftagram**.\
Since I'm assuming you checked your connection and everything, are you perhaps using LittleSnitch or something similar?\
Did you try it on an actual device?

**Comment by senolatac** [comment]
hey @sbertix 
Details:
- WebViewAuthenticator 
- Same error on real device.
- It's not related with network.
- 2FA is not sms-message, it's authenticator-tool...

But I think that it's a common problem because I tested it on live third party applications. They have this problem also. But it works on instagram self site very well.

**Comment by sbertix** [comment]
Okay... so if it's an issue with `WebViewAuthenticator`, and it involves the webpage per se, I think there's not much I can do about it...\
I tried it again and it works for me 😢\
Are you perhaps using a custom user agent?

**Comment by senolatac** [comment]
Thanks for your investigation @sbertix 
Most probably, it's related with my account.
