### ISSUE TITLE
Fetch Email Address of current user

### ISSUE THREAD

**Issue by senolatac** [sbertix/Swiftagram#65]
- [x] I've searched past issues and I couldn't find reference to this. 
- [x] I've checked out all provided _Examples_.

**Info**  
Write your question or whatever you need, related to **Swiftagram**.

How can I fetch email address of current user with using Swiftagram Endpoint?

**Comment by sbertix** [comment]
It's not currently in the repository by choice, as I don't want people to spam users (also linked to your other password issue), but the endpoint is out there, and you should be able to extend `Endpoint` with it super easily by looking at how all others are implemented.

**Comment by sbertix** [comment]
If you need further instructions, [send me a message](https://telegram.me/sbertix) @senolatac
