### ISSUE TITLE
Retrieve password from Secret

### ISSUE THREAD

**Issue by senolatac** [sbertix/Swiftagram#66]
- [x] I've searched past issues and I couldn't find reference to this. 
- [x] I've checked out all provided _Examples_.

**Info**  
Write your question or whatever you need, related to **Swiftagram**.

Is it possible to retrieve Password of current user from Secret or Keychain?

**Comment by sbertix** [comment]
No, there's no way to do so.\
`Authenticator` are agnostic in the way they handle authentication by choice, not expecting a password, and definitely never persisting it.\
Not only that, it's already a big privacy concern using authentication cookies like we do, having direct control over a user's password is much much worse.

That said, should you require that, you shouldn't have trouble implementing it forming the repo for yourself, but I strongly advice against messing with users' passwords.
