### ISSUE TITLE
Updating Followers to `4.0.0` results in crash

### ISSUE THREAD

**Issue by joshuazmiller** [sbertix/Swiftagram#68]
Hey @sbertix!

Just upgraded to 4.0. Great stuff! Thank you!

Question about the purpose of the following snippet in the example code:

```
// Keep `UserDefaults` in sync.
// This will only persist new `User`s, not delete old ones: this is just an example.
$current.compactMap { $0 }
     .removeDuplicates(by: { $0.identifier == $1.identifier })
     .map { (data: try? JSONEncoder().encode($0), id: $0.identifier) }
     .sink { UserDefaults.standard.set($0.data, forKey: $0.id) }
     .store(in: &subscriptions)
```

What does this snippet aim to accomplish? What negative things might happen when omitting this snippet?

---

I got `Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value:` 
for this line: 
`.map { (data: try? JSONEncoder().encode($0), id: $0.identifier) }`

**Comment by sbertix** [comment]
Thanks man :blush:
It simply persists `current` in `UserDefaults` so it's already available on next launch.\
Weird that it fails though… what Xcode version are you on? @joshuazmiller

**Comment by joshuazmiller** [comment]
I'm on XCode Version 11.6 (11E708). Cleaning the project didn't solve...

**Comment by sbertix** [comment]
Could you add `Logger.level = .full` at the beginning of `init` and paste the content of the `User` response?\
Apparently you get a `User` back, but for some reason the primary key is not parsed correctly… 🤔

**Comment by joshuazmiller** [comment]
The User model stored in `current` does appear to properly have the identifier as I see `identifier: Optional("012345678")` inside it. I think it's the mapping code that has a nil value in it...

**Comment by sbertix** [comment]
I can actually just remove the code, tbh, but I would really like to fix it, but I can't make it crash myself… 😢\
Thing is the mapping just encodes the underlying `Wrapper` you receive, after making sure `User` is non-nil, so it shouldn't cause any `identifier`-related issues.\

> I really do think it's from the mapping code, but I'm gonna explore a bit deeper and report back.
Thanks. Let me know if you get to narrow it down 💪

**Comment by sbertix** [comment]
Do you mind resetting the SPM package cache (as it might have locked an earlier version of **ComposableRequest** that had a related issue) and changing the code to the snippet below?\
Cause if it's related to `identifier` it must show it's `nil` there.

```swift
        $current
            .compactMap { $0 }
            .removeDuplicates(by: { $0.identifier == $1.identifier })
            .print()
            .map { (data: try? JSONEncoder().encode($0), id: $0.identifier) }
            .sink { UserDefaults.standard.set($0.data, forKey: $0.id) }
            .store(in: &subscriptions)
```

**Comment by joshuazmiller** [comment]
I believe I figured out what is going on..

Well what if someone already persisted a model that didn't have the underlying identifier in it? For instance, say you were to manually persist to `UserDefaults` a partial `User` model object (like a custom object) that was missing the `identifier`. Then this value would be nil and cause the crash.

So, I had been experimenting with a custom User model called `GramModel` in my project so as to not have the definition of User confined to the Swiftagram's definition. But after running the update I decided to accept `User` over my `GramModel` since you have a more advanced model now. But `UserDefaults` already persisted the old version with the `nil` for `identifier`.

You aren't seeing the crash because you kept the model consistent at least since the last install of whatever app you use to test...

Did 3.0 have this `identifier` in the model? Because if `identifier` is not present in previous versions, then when apps rollout with this update then I would expect to see this crash among existing users.

But I think this can be solved with an update to where this code is. Currently I see it being placed in an area where it'll be executed even on old storage of `$current` where `identifier` may not be present if the model was different in the past.

Moving like this below snippet resolves the issue for the change in User model for me and appears to solve the crash..

```
/// The logged in user.
    @Published var current: User? {
        didSet {
            // Keep `UserDefaults` in sync.
            // This will only persist new `User`s, not delete old ones: this is just an example.
            $current.compactMap { $0 }
                .removeDuplicates(by: {
                    $0.identifier == $1.identifier
                })
                .map {(data: try? JSONEncoder().encode($0), id: $0.identifier ?? "currentUser")}
                .sink { UserDefaults.standard.set($0.data, forKey: $0.id) }
                .store(in: &subscriptions)
        }
    }
```

**Comment by sbertix** [comment]
Yep… this is a new addition to `4.0.0`.\
As **Followers** is supposed to just be an example, this should virtually affect nobody.\
Despite not being urgent, as it's not a bug in the codease, I'm stilling adding a method to delete previous versions persisted defaults in `4.1.0`.\
Thank you 💪
