### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by joshuazmiller** [sbertix/Swiftagram#69]
- [x] I've searched past issues and I couldn't find reference to this. 

**Swiftagram version**
`4.0.0`

**Describe the bug**
Unable to archive build for distribution. Get `Integer literal '9999999999' overflows when stored into 'Int'` error upon compilation.

**To reproduce**
1. Compile for Generic iOS device
2. iOS deployment target is 13.0

**Expected behavior**
Compilation should work.

**Additional context**
<img width="960" alt="Screen Shot 2020-08-18 at 5 32 10 PM" src="https://user-images.githubusercontent.com/20162542/90578916-5a453980-e179-11ea-8613-a6411f0c94e7.png">

**Device and system**
macOS 10.15.5, Generic iOS Device, Xcode 11.6

**Comment by sbertix** [comment]
I'm assuming you're running it on a 32-bit architecture, as `Int` is only the same size of `Int64` on 64-bit ones.\
I didn't consider that might be a problem.\
I'm pushing an update rn.

**Comment by joshuazmiller** [comment]
No worries :). Thank you! I believe I'm on a 64-bit though. My Mac is an Intel i9...

**Comment by sbertix** [comment]
Then I have no clue why `Int` would not allow for a value way smaller than `9,223,372,036,854,775,807` hahaha
Either way, let me know if this fixes it 💪

**Comment by joshuazmiller** [comment]
Yup, it succeeds now! Thanks! 👍

**Comment by sbertix** [comment]
Thank you man for pointing it out so I could fix it for everyone 💪
