### ISSUE TITLE
Add `code` and `hasLiked` to `Media`

### ISSUE THREAD

**Issue by NathanFallet** [sbertix/Swiftagram#74]
- [x] I've searched past issues and I couldn't find reference to this. 

**Is your feature request related to a problem? Please describe.**
Some missing properties to media

**Describe the solution you'd like**
Add theses properties to `Media` struct

**Comment by sbertix** [comment]
Thanks man.\
Do you mind amending the commit so that it follows naming guidelines (i.e. changing it to _Add `code` and `hasLiked` to `Media`_)?\
I'm merging it into `4.0.3` later together with the uploading fix (hopefully).
