### ISSUE TITLE
How to paginate one page at a time?

### ISSUE THREAD

**Issue by mycroftcanner** [sbertix/Swiftagram#78]
I want to be able to load a number of pages at a certain rate and then resume synchronisation at a much later time if necessary. 

In README.md it says we can use `.task(maxLength: 10, ...)` and just resume().  However, I'd rather save a cursor and be able to resume using `startingAt` even my app gets killed by the system.

I couldn't figure out a way to get a cursor.

**Comment by sbertix** [comment]
Hey @mycroftcanner.\
I'm actually adding "pre-parsed" support for pagination parameters in `4.1.0` (the `development` branch should provide an initial working version).\
Otherwise, for now, I suggest simply inspecting the underlying `Wrapper`.

```swift
   […]
   .task {
      guard let response = try? $0.get() else { return nil }
      // most endpoints (I'd say all except the Direct ones), store next cursor in `next_max_id`.
      print(response["nextMaxId"].string() as Any)
   }
   .resume()
```
