### ISSUE TITLE
Getting error after update

### ISSUE THREAD

**Issue by MariaJsn** [sbertix/Swiftagram#83]
I update the latest version of Api and I am getting following error for some users and app crash. 
Before update I did not get any error like this. Is it related with Swiftagram library?

Error:
#1 (null) in partial apply for thunk for @escaping @callee_guaranteed (@guaranteed Result<TrayItemUnit, Error>) -> () ()

Thanks,
Maria

**Comment by sbertix** [comment]
Hey @MariaJsn 😊\ 
Do you mind sharing the bit of code that appears to be producing the error?\ 
What versions were you on and what version of **Swiftagram** are you on now?

**Comment by MariaJsn** [comment]
Hi Sbertix :)
I do not have to much detail about error. Some of the users getting error and after that app crashed. I tried many time and did not get any error with my account. I get this error from Xcode organizer crashes.
Before I was using 3.1.1 and updated to 4.0.3 version

**Comment by sbertix** [comment]
Do you mind sharing at least the symbolication error?\
You can send it to me on [telegram](telegram.me/sbertix).

**Comment by egasteam** [comment]
Yes I understand you, not I am checking the how I can get the symbolicated log file :)

**Comment by MariaJsn** [comment]
So sorry my stupid question but how can I create/get a symbolicated log?

**Comment by sbertix** [comment]
The crash logs you get from `Xcode` should already be symbolicated 😊\
Just send that if you can.\
And don't worry it's not a stupid question 💪

**Comment by MariaJsn** [comment]
Sorry Sbertix I am not using telegram. I uploaded to wetransfer.
This is the link of the symbolicated file. https://we.tl/t-8yaUotWT1K

**Comment by sbertix** [comment]
Mmh 🤔 it does not seem to be related to **Swiftagram** per se, but with something that happens when the response closure fires.\
Do you mind sharing the code for `Followers.swift`? You can send it to stefano@bertagno.com, you don't have to make it public. I'm assuming at row 17, you're making the call and then something happens.

**Comment by MariaJsn** [comment]
import RealmSwift

class Followers: Object {
    
    @objc dynamic var Id = 0
    @objc dynamic var userName = ""
    @objc dynamic var fullName = ""
    @objc dynamic var profilePicUrl = "" //Line 17
}

**Comment by sbertix** [comment]
So I guess the issue is, as always, related to `Realm`. 😊\
Are you perhaps passing `Realm` or `Object` instances around? Or strongly referencing them, instead of recreating them every time by referencing their `primaryKey`, or using the appropriate thread safe wrappers?

**Comment by MariaJsn** [comment]
I am happy to be not related with Swiftagram. I am using id for primary key and It was working. Then it means realm updated codes and borek something. I will check the realm part deeply.
Thanks for your all help Sbertix. You are the king :)
