### ISSUE TITLE
Instagram Api

### ISSUE THREAD

**Issue by aslios** [sbertix/Swiftagram#84]
Hi Sbertix,
Can i ask u something ?
I need  android private instagram api like yours.Do u know that ? i need api which contains original instagram login.If you know can u share with me ?

Thank You

**Comment by sbertix** [comment]
Hey @aslios 😊 
I'm sure by search for "Instagram Private API" and the programming language you're writing your app in, you should find several entries. Unfortunately I don't have one to recommend. 
Good luck :v:
