### ISSUE TITLE
KeychainStorage with iOS version 12

### ISSUE THREAD

**Issue by MariaJsn** [sbertix/Swiftagram#85]
Hey Sbertix :)

When I tried to open app I am getting error from KeychainStorage with iOS version 12.4.

My code:
"KeychainStorage< Secret >().removeAll()" or "KeychainStorage< Secret >().all().first"

Can we fix this issue please?

**Comment by sbertix** [comment]
Hey 👋 
I can't test it right now. Do you mind telling me more about the error you're getting? 
I'm assuming it's an issue with **KeychainSwift** thought, right?

**Comment by MariaJsn** [comment]
Yes you are correct, there is an issue in KeychainSwift.
I am getting error in that line and application crashed. It says 'EXC_BAD_ACCESS', There is no more detail message

**Comment by MariaJsn** [comment]
Sbertix is there any news about error?

**Comment by sbertix** [comment]
I didn't have the chance to actually look into it, unfortunately, as I'm not home. 
But, as it appears to be **KeychainSwift** related, I suggest maybe filing an issue on their repo, although it looks like it might be discontinued. 
I might look for an alternative implementation in the meanwhile.

**Comment by MariaJsn** [comment]
I already opened an issue for KeychainSwift. When you come back to your home please can you check it too? I am sure you can find better solution.

**Comment by sbertix** [comment]
I will 💪 
And sorry for the delay.

**Comment by MariaJsn** [comment]
Ok waiting your repsonse :)

**Comment by sbertix** [comment]
I've pushed an update for [**ComposableRequest**](https://github.com/sbertix/ComposableRequest) with a workaround for `KeychainSwift` thread-safety issues. 
By updating **Swiftagram** to the last version, and reloading SPM cache, it should all work now. 
Let me know @MariaJsn

**Comment by MariaJsn** [comment]
Hi Sbertix,
It did not work for me. I update the Swiftagram library (also try with to remove Swiftagram and added again) then remove application from simulator which has IOS 12.4 version. Cleaned build folder and run it. But I get the same error in "KeychainStorage<Secret>().removeAll()" code.

**Comment by sbertix** [comment]
Does it say you're using `ComposableRequest 4.2.2` in Xcode? @MariaJsn 
Otherwise it looks like the issue might not be one of thread safety, like people were suggesting in your issue at **KeychainSwift** :cry:

**Comment by MariaJsn** [comment]
yes ComposableRequest 4.2.2 in Xcode. Really I could not understand the real issue. I am trying to find solution last 1 week but I could not find anything.

**Comment by MariaJsn** [comment]
@sbertix Do you have any suggestion for this error? Also it was working before update the latest version of Swiftagram.

**Comment by sbertix** [comment]
Nothing was changed in the implementation of `KeychainStorage` before the update I pushed yesterday, meaning the bug you're getting either depends on **KeychainSwift** or your implementation. 
I wasn't even capable of replicating it, meaning it's probably either a "case specific" occurrence for your code. 
If you wanna share the code that raises the error, I'm more than happy to give it a look for you.

**Comment by MariaJsn** [comment]
@sbertix you can find code in below link. It is working witj ios 13 and 14 but not working with ios 12.4
https://we.tl/t-CPNeSKoIko

**Comment by MariaJsn** [comment]
Hey @sbertix 
Did you get the same error like me?

**Comment by MariaJsn** [comment]
@sbertix Sorry to disturb you, do you have any update?

**Comment by sbertix** [comment]
I do, and after googling for a while, I feel like this might not even be a **KeychainSwift** problem, but a Swift compiler one, meaning there's nothing anyone can do, tbh. 
Sorry.

**Comment by MariaJsn** [comment]
Ok I will try to store in local storage if version is 12. Thanks for your all help @sbertix

**Comment by sbertix** [comment]
I'm testing a different implementation of a keychain wrapper as we speak. 
Do not change your code yet as I might be able to make `KeychainStorage` work.

**Comment by sbertix** [comment]
Nope. Still not working. Sorry :cry:

**Comment by MariaJsn** [comment]
It is a really stupid bug and nothing clear. I am trying to store Secret value in a different way but it is not working yet

**Comment by MariaJsn** [comment]
@sbertix Is there any way to store secret in realm db or userdefaults? (I tried but I could not find a way)

**Comment by sbertix** [comment]
Sure. Just use `UserDefaultsStorage` instead of `KeychainStorage`. 
No need to store it yourself btw, you can pass it directly to `WebViewAuthenticator` on init with 

```swift
let storage = /* some Storage */
WebViewAuthenticator(storage: storage) { _ in }
```

**Comment by MariaJsn** [comment]
I could not implement like you suggest, but when I tried like this: (If I use like this defaults.set gives an error like Attempt to insert non-property list object Swiftagram.Secret)

          WebViewAuthenticator { self.webView = $0 }
              .authenticate {
                  switch $0 {
                  case .failure(let error): print(error.localizedDescription)
                  case .success(let secret):
                    let defaults = UserDefaults.standard
                    defaults.set(secret, forKey: "secret")
                    
                    //let storage = KeychainStorage<Secret>()
                    //storage.store(secret)
                    
                }
        }

**Comment by sbertix** [comment]
You're not using `UserDefaultsStorage`, just `UserDefaults`.
Replace your code with this one.

```swift
WebViewAuthenticator(storage: UserDefaultsStorage<Secret>()) { self.webView = $0 }
   .authenticate {
      switch $0 {
         case .failure(let error): print(error.localizedDescription)
         case .success: break // Returned `Secret` is already stored by the `WebViewAuthenticator`.
      }
   }
```

**Comment by MariaJsn** [comment]
Thank you very much :)
But this way did not work for iso 12 too :(
I think there is no chance to work it with ios 12 😢😢😢😢

**Comment by sbertix** [comment]
Hey @MariaJsn, I'm pushing **Swiftagram** `4.1.3` hopefully fixing this nasty bug. 
Let me know if it works for you 💪

**Comment by MariaJsn** [comment]
Yesss. It is working. 
You make my day more beautiful.
Thank you very much. I am so appreciated.
You are the king.
