### ISSUE TITLE
How to call Follow & Unfollow requests?

### ISSUE THREAD

**Issue by karorox** [sbertix/Swiftagram#88]
- [x] I've searched past issues and I couldn't find reference to this. 
- [x] I've checked out all provided _Examples_.

**Info**  
Give me examples of calling Follow & Unfollow requests.

**Comment by sbertix** [comment]
Hey @karorox 

Just import `SwiftagramCrypto` and you can do something like…

```swift
import Swiftagram
import SwiftagramCrypto

/// Your authentication `Secret` you obtained from an `Authenticator`.
let secret = /* some Secret */
/// The identifier for the user you want to follow.
let identifier = /* some String */
/// Execute the request.
Endpoint.Friendship.follow(identifier)
   .unlocking(with: secret)
   .task { _ in  /* analyze the response */ }
   .resume()
```

**Comment by galblank** [comment]
@sbertix  - there is no Friendship or follow option available for some reason , am I missing something ? 
thanks
