### ISSUE TITLE
Minimum Platform Error

### ISSUE THREAD

**Issue by senolatac** [sbertix/Swiftagram#91]
- [x] I've searched past issues and I couldn't find reference to this. 

**Swiftagram version**
4.1.3

**Describe the bug**
error: The package product 'Swiftchain' requires minimum platform version 9.0 for the iOS platform, but this target supports 8.0 (in target 'ComposableRequestCrypto' from project 'ComposableRequest')

**To reproduce**
When I try to build it to target: IOS, IOS13...

**Expected behavior**
Build successfull

**Device and system**
iPhone Simulator 13.7

**Comment by sbertix** [comment]
Hey @senolatac 💪
Does this happen regardless of your minimum platform version? 
What is it currently set on for your project?

**Comment by senolatac** [comment]
<img width="597" alt="Screen Shot 2020-10-24 at 4 02 57 PM" src="https://user-images.githubusercontent.com/27292083/97082467-9c27ab80-1612-11eb-9fb1-23fb8a8e0864.png">

Yes, it's regardless of my target version.

**Comment by senolatac** [comment]
When I set it as iOS 13.0, it doesn't work also. @sbertix FYI.

**Comment by sbertix** [comment]
What version of Xcode are you on? 
Does it still happen after resetting and updating the SPM dependencies and cleaning the project's derived data? 
I can't seem to replicate it so apologies if I need to ask more questions.

**Comment by sbertix** [comment]
I'm still gonna hardcode version dependencies as soon as I get to it. Hopefully I can fix it by tomorrow.

**Comment by senolatac** [comment]
Xcode: 11
Derived data removed.
SPM dependencies updated.

But error is same.

**Comment by sbertix** [comment]
`4.1.4` explicitly specifies minimum platform versions. 
This should fix it, if the error was indeed related to it. 
Let me know.
