### ISSUE TITLE
'nil' requires a contextual type Error in last version

### ISSUE THREAD

**Issue by i-Senku** [sbertix/Swiftagram#99]
I updated to last version and when i build project i get 'nil' requires a contextual type error in Client.swift.
How can i fix that ?

**Comment by sbertix** [comment]
Hey @i-Senku 💪 
Where exactly are you getting the error?

**Comment by i-Senku** [comment]
I'm getting the same error

<img width="284" alt="Ekran Resmi 2020-11-02 14 45 40" src="https://user-images.githubusercontent.com/54575884/97864722-1e525700-1d1a-11eb-9363-c66e1b1ee0f6.png">
<img width="871" alt="Ekran Resmi 2020-11-02 14 46 18" src="https://user-images.githubusercontent.com/54575884/97864766-34601780-1d1a-11eb-9d97-2c06b9c3c885.png">

**Comment by sbertix** [comment]
You need to update the SPM. 
As you can see, your code is still the one from `4.2.0`: [this is how it looks now](https://github.com/sbertix/Swiftagram/blob/main/Sources/Swiftagram/Client/Client.swift)

**Comment by sbertix** [comment]
It should work now. Apologies
